name: Pararel Autoblog Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: '00 01 * * *'
  

jobs:
  main-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Eksekusi aksi pararel autoblog
        run: |
          curl -X GET "https://blogkeren.web.id/create_repo.php?user_id=13&api_key=BKfBcagtEUHy&start=1" 